### ISSUE TITLE
Error: taskdef class org.apache.tools.ant.taskdefs.optional.RasterizerTask cannot be found

### ISSUE THREAD

**Issue by aidanreilly** [dita-semia/org.dita-semia.image-convert#1]
Hi Patrik,

Me again :) just trying out some of your plugins. Your talk at DITA Europe was very interesting. I'm trying out the org.dita-semia.image-convert plugin with 3.2 OT. 

When I run:

dita --input C:\Users\jreillai\Desktop\schematron_test\2081-0006.ditamap --format=html5-bootstrap -Ddita-semia.image-convert.activate=true -Ddita-semia.image-convert.dest-format=png

I get an error: Error: taskdef class org.apache.tools.ant.taskdefs.optional.RasterizerTask cannot be found

Ive tried setting 		<taskdef name="rasterize" classname="org.apache.tools.ant.taskdefs.optional.RasterizerTask" classpath="plugins/org.dita-semia.image-convert/lib"/> in org.dita-semia.image-convert\preprocess.image-convert.xml

Error still occurs. Am I missing something obvious?

**Comment by PStellmann** [comment]
Hi Aidan,

it was me who missed something obvious... ;)

I could reproduce your error by using a clean oXygen transformation scenario and managed to resolve it.

please update the plugin.xml I just commited and try again after another run of the integrator.

**Comment by aidanreilly** [comment]
Hi Patrik,

Thanks for the quick response. I get an error after updating the above: 

C:\dita-ot-3.2>dita --input C:\Users\jreillai\Desktop\schematron_test\2081-0006.ditamap --format=html5 -Ddita-semia.imag
e-convert.activate=true -Ddita-semia.image-convert.dest-format=png

Error: Problem: failed to create task or type if
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

**Comment by PStellmann** [comment]
I started to test it outside oXygen and identified two more issues:
1. To make the if task working ant-contrib needs tb be registeres - which I have added
2. There was another library missing to make batik work - which I have added as well.

So please try it again with latest sources.

**Comment by aidanreilly** [comment]
OK thank you will try again.

**Comment by aidanreilly** [comment]
OK! this works well, thanks Patrik!
